name: Schedule test

on:
  schedule:
    - cron: '0 * * * *'  # every hour at minute 0 (UTC)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print timestamp
        run: |
          echo "Schedule test run at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > schedule_test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: schedule_test_artifact
          path: schedule_test.txt
