name: Weekly paper fetch

on:
  schedule:
    - cron: '59 3 * * 1'  # every Monday at 03:59 UTC (~23:59 Sunday US Eastern during DST)
  workflow_dispatch: {}

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        run: |
          python fetch_papers.py --weekly --rows 200 --last-days 30 --query "pig OR swine"

      - name: Record last success timestamp
        if: ${{ success() }}
        run: |
          mkdir -p weekly
          echo "Last success: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > weekly/last_success.txt

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weekly/*.md weekly/last_success.txt journals_issn.txt || true
          git commit -m "Weekly: fetch latest swine papers" || echo "No changes to commit"
          git push
